language: php

php:
    - 7.1

install:
    - composer selfupdate
    - composer install

before_script:
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:schema:update --force --env=test
    - php bin/console doctrine:fixture:load -n --env=test
    - php bin/console maba:webpack:compile --env=test

script:
    - ./vendor/bin/php-cs-fixer fix --diff --dry-run
    - ./vendor/bin/phpunit --colors