user:
    resource: "@UserBundle/Resources/config/routing.yml"

app:
    resource: "@AppBundle/Resources/config/routing/routing.yml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"