admin_categories:
    path: /admin/categories
    defaults:
        _controller: AppBundle:Category:show
    methods: [GET]

admin_update_category:
    path: /admin/update-category/{id}
    defaults:
        _controller: AppBundle:Category:update
    methods: [POST]

admin_new_category:
    path: /admin/create-category
    defaults:
        _controller: AppBundle:Category:create
    methods: POST