delete_comment:
    path: /delete
    defaults:
        _controller: AppBundle:Comment:delete
    methods: [POST]

edit_comment:
    path: /edit
    defaults:
        _controller: AppBundle:Comment:edit
    methods: [POST]

