homepage:
    path: /
    defaults:
        _controller: AppBundle:Home:index
    methods: [GET]

post_show:
    path: /post/{slug}
    defaults:
        _controller: AppBundle:Post:show
    methods: [GET, POST]

lists_posts_category:
    path: /category/{categorySlug}
    defaults:
        _controller: AppBundle:Post:category
    methods: [GET]

lists_posts:
    path: /posts
    defaults:
        _controller: AppBundle:Post:listPosts
    methods: [GET]

list_posts_author:
    path: /author/{idAuthor}
    defaults:
        _controller: AppBundle:Post:author
    methods: [GET]

new_post:
    path: /new-post
    defaults:
        _controller: AppBundle:Post:newPost
    methods: [GET, POST]

edit_post:
    path: /edit-post/{slug}
    defaults:
        _controller: AppBundle:Post:edit
    methods: [GET, POST]