homepage:
    path: /
    defaults:
        _controller: AppBundle:Home:index
    methods: [GET]

google_webmaster_tool:
    path: /googlefa873c3cd12e50af.html
    defaults:
        _controller: AppBundle:Home:googleWebMasterTools
    methods: [GET]


admin_dashboard:
    path: /admin/dashboard
    defaults:
        _controller: AppBundle:Admin:dashboard
    methods: [GET]

admin_dashboard_users:
    path: /admin/dashboard/users
    defaults:
        _controller: AppBundle:Admin:users
    methods: [GET]

admin_user_delete:
    path: /admin/delete-user/{id}
    defaults:
        _controller: AppBundle:Admin:deleteUser
    methods: [DELETE]

admin_user_edit_role:
    path: /admin/edit-role/{id}
    defaults:
        _controller: AppBundle:Admin:editRole
    methods: [POST]

super_admin_search_user:
    path: /admin/search-user
    defaults:
        _controller: AppBundle:Admin:searchUser
    methods: [POST]

lists_posts:
    path: /posts
    defaults:
        _controller: AppBundle:Post:posts
    methods: [GET]

posts:
    resource : "@AppBundle/Resources/config/routing/posts_routing.yml"
    prefix: /posts

category:
    resource: "@AppBundle/Resources/config/routing/category_routing.yml"

twitter:
    resource: "@AppBundle/Resources/config/routing/twitter_routing.yml"
    prefix: /admin

like:
    resource: "@AppBundle/Resources/config/routing/like_routing.yml"
    prefix: /ajax

comment:
    resource: "@AppBundle/Resources/config/routing/comment_routing.yml"
    prefix: /comment