services:
    twitter.api:
        class: AppBundle\Twitter\Twitter
        arguments:
            - "%twitter_consumer_key%"
            - "%twitter_consumer_secret%"
            - "%twitter_brohazard_access_token%"
            - "%twitter_brohazard_access_token_secret%"
            - "%kernel.environment%"

    twitter.autolink_extension:
        class: AppBundle\Twitter\AutolinkExtension
        tags:
            - { name: twig.extension }
